import { test, expect } from '@playwright/test';


test.describe('Case 2', () => {

    test('case2-success', async ({ page }) => {
        await page.goto('https://automationexercise.com/');
        await page.locator('div').filter({ hasText: 'Home  Products Cart Signup' }).first().click();
        await page.locator('#slider').click();
        await page.locator('section').filter({ hasText: 'Category Women Dress Tops' }).click();
        await page.getByRole('link', { name: ' Signup / Login' }).click();
        await page.getByRole('heading', { name: 'New User Signup!' }).click();
        await page.getByRole('textbox', { name: 'Name' }).click();
        await page.getByRole('textbox', { name: 'Name' }).fill('Isaac');
        await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
        await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('email@email.com');
        await page.getByRole('button', { name: 'Signup' }).click();
        await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').click();
        await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').fill('amogus@crewmate.com');
        await page.getByRole('button', { name: 'Signup' }).click();
        await page.getByRole('radio', { name: 'Mr.' }).check();
        await page.getByRole('textbox', { name: 'Password *' }).click();
        await page.getByRole('textbox', { name: 'Password *' }).fill('password123');
        await page.locator('#days').selectOption('30');
        await page.locator('#months').selectOption('6');
        await page.locator('#years').selectOption('2003');
        await page.getByRole('checkbox', { name: 'Sign up for our newsletter!' }).check();
        await page.getByRole('checkbox', { name: 'Receive special offers from' }).check();
        await page.getByRole('textbox', { name: 'First name *' }).click();
        await page.getByRole('textbox', { name: 'First name *' }).fill('Isaac');
        await page.getByRole('textbox', { name: 'Last name *' }).click();
        await page.getByRole('textbox', { name: 'Last name *' }).fill('Sanchez');
        await page.getByRole('textbox', { name: 'Company', exact: true }).click();
        await page.getByRole('textbox', { name: 'Company', exact: true }).fill('company');
        await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).click();
        await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('random street 342');
        await page.getByRole('textbox', { name: 'Address 2' }).click();
        await page.getByRole('textbox', { name: 'Address 2' }).fill('random street 2');
        await page.getByLabel('Country *').selectOption('United States');
        await page.getByRole('textbox', { name: 'State *' }).click();
        await page.getByRole('textbox', { name: 'State *' }).fill('NY');
        await page.getByRole('textbox', { name: 'City * Zipcode *' }).click();
        await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('idk');
        await page.locator('#zipcode').click();
        await page.locator('#zipcode').fill('99999');
        await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
        await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('8100000000');
        await page.getByRole('button', { name: 'Create Account' }).click();
        await page.getByText('Account Created!').click();
        await page.getByText('Account Created! Congratulations! Your new account has been successfully').click();
        await page.getByRole('link', { name: 'Continue' }).click();
        await page.getByText('Logged in as Isaac').click();
        await page.getByRole('link', { name: ' Delete Account' }).click();
        await page.getByText('Account Deleted!').click();
        await page.locator('div').filter({ hasText: 'Account Deleted! Your account' }).nth(1).click();
        await page.getByRole('link', { name: 'Continue' }).click();
    });

    test('case2-fail', async ({ page }) => {
        await page.goto('https://automationexercise.com/');
        await page.locator('div').filter({ hasText: 'Home  Products Cart Signup' }).first().click();
        await page.locator('#slider').click();
        await page.locator('section').filter({ hasText: 'Category Women Dress Tops' }).click();
        await page.getByRole('link', { name: ' Signup / Login' }).click();
        await page.getByRole('heading', { name: 'New User Signup!' }).click();
        await page.getByRole('textbox', { name: 'Name' }).click();
        await page.getByRole('textbox', { name: 'Name' }).fill('Isaac');
        await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
        await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('email@email.com');
        await page.getByRole('button', { name: 'Signup' }).click();
        await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').click();
        await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').fill('amogus@crewmate.com');
        await page.getByRole('button', { name: 'Signup' }).click();
        await page.getByRole('radio', { name: 'Mr.' }).check();
        await page.getByRole('textbox', { name: 'Password *' }).click();
        await page.getByRole('textbox', { name: 'Password *' }).fill('password123');
        await page.locator('#days').selectOption('30');
        await page.locator('#months').selectOption('6');
        await page.locator('#years').selectOption('2003');
        await page.getByRole('checkbox', { name: 'Sign up for our newsletter!' }).check();
        await page.getByRole('checkbox', { name: 'Receive special offers from' }).check();
        await page.getByRole('textbox', { name: 'First name *' }).click();
        await page.getByRole('textbox', { name: 'First name *' }).fill('Isaac');
        await page.getByRole('textbox', { name: 'Last name *' }).click();
        await page.getByRole('textbox', { name: 'Last name *' }).fill('Sanchez');
        await page.getByRole('textbox', { name: 'Company', exact: true }).click();
        await page.getByRole('textbox', { name: 'Company', exact: true }).fill('company');
        await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).click();
        await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('random street 342');
        await page.getByRole('textbox', { name: 'Address 2' }).click();
        await page.getByRole('textbox', { name: 'Address 2' }).fill('random street 2');
        await page.getByLabel('Country *').selectOption('United Stats');
        await page.getByRole('textbox', { name: 'State *' }).click();
        await page.getByRole('textbox', { name: 'State *' }).fill('NY');
        await page.getByRole('textbox', { name: 'City * Zipcode *' }).click();
        await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('idk');
        await page.locator('#zipcode').click();
        await page.locator('#zipcode').fill('99999');
        await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
        await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('8100000000');
        await page.getByRole('button', { name: 'Create Account' }).click();
        await page.getByText('Account Created!').click();
        await page.getByText('Account Created! Congratulations! Your new account has been successfully').click();
        await page.getByRole('link', { name: 'Continue' }).click();
        await page.getByText('Logged in as Isaac').click();
        await page.getByRole('link', { name: ' Delete Account' }).click();
        await page.getByText('Account Deleted!').click();
        await page.locator('div').filter({ hasText: 'Account Deleted! Your account' }).nth(1).click();
        await page.getByRole('link', { name: 'Continue' }).click();
    });


});